### ISSUE TITLE
Cache issues and questions

### ISSUE THREAD

**Issue by newhoggy** [haskell-mafia/mafia#103]
Does anyone know what to do when encountering this error?

```
Installing dependencies...
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hw-succinct-0.0.0.8 (user goal)
next goal: hw-rankselect (dependency of hw-succinct-0.0.0.8)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Process failed: cabal install --reorder-goals --max-backjumps=-1 --avoid-reinstalls --dry-run --enable-tests --enable-benchmarks --enable-profiling (exit code: 1)
```

**Comment by tmcgilchrist** [comment]
Try `mafia update` to upgrade your cabal package list.

**Comment by jacobstanley** [comment]
> Try `mafia update` to upgrade your cabal package list.

I think `hw-rankselect` is source dependency, so this probably won't help.

@newhoggy got a link to the repo? it looks like mafia isn't finding the cabal file for `hw-rankselect` in your git repository, or in a submodule.

**Comment by newhoggy** [comment]
The repository does not have a `.submodules` file.

Here is the failing build:
- https://circleci.com/gh/haskell-works/hw-succinct/528

Rebuild without cache works:
- https://circleci.com/gh/haskell-works/hw-succinct/530

They are both building against commit id `06c5f83`.

This commit id is tagged and can be viewed here: `https://github.com/haskell-works/hw-succinct/tree/v0.0.0.8`

Even though there is no `.submodules` file, I may have had such a file somewhere earlier in the history of the project.  Is it possibly that `mafia` has stored some state about the `.submodules` file and is failing because of that despite having removed it?

**Comment by jacobstanley** [comment]
Ok I think I misunderstood, I guess `hw-rankselect` is not supposed to be a source dependency, but should come from hackage?

I noticed that you are caching `/home/ubuntu/hw-succinct/.cabal-sandbox`, I wonder if removing that from the cache might make it work.

**Comment by newhoggy** [comment]
I'm not caching the `/home/ubuntu/hw-succinct/.cabal-sandbox`, at least not intentionally.

The `circle.yml` file specifies the following: directories for caching:

```
  cache_directories:
    - "~/.ambiata"
    - "~/.cabal"
    - "~/.ghc"
```

Could `~/.cabal` or `~/.ghc` be the problem?

**Comment by markhibberd** [comment]
@newhoggy I think it could be back to what @tmcgilchrist said originally, hw-rankselect has only been on hackage for a day so unless you have run `cabal update` it doesn't know about it which makes it looks like a submodule  in the error message, the cache for `cabal update` is in `~/.cabal` so it would be persisted between builds. If you _are_ running `mafia update` you should note it only updates from hackage once a day so depending on timings it may not of picked up that version yet (but would tomorrow), if you want to force it you could run `cabal update` directly. The only other possibility which I only mention because I have no idea about the innards of circle-ci is that if it does something dumb with sync the cache (for example updating the timestamp rather than keeping the original file attributes) it might mess with how `mafia update` determines how fresh the pacakges file from hackage is.

**Comment by newhoggy** [comment]
Cool.  I think I have the information I need to know what to look out for.  Currently my builds aren't in this state so I'll wait till it happens again, then take a look and report back.

Thanks!

**Comment by novemberkilo** [comment]
Looks like this issue can be closed? // @newhoggy @tmcgilchrist

**Comment by newhoggy** [comment]
Sorry, I haven't been using `mafia` for a while now, so I'm unable to contribute more to this ticket.  I think it is appropriate to close this ticket.
