### ISSUE TITLE
Hoogle 5.x support

### ISSUE THREAD

**Issue by charleso** [haskell-mafia/mafia#198]
Mafia currently uses the `combine` command from hoogle 4.x which is no longer supported in hoogle 5.x.

The solution appears to be to use the [generate](https://github.com/ndmitchell/hoogle/blob/14744b833b0aaf079560065fb031ee7a5860ab63/src/Action/Generate.hs#L65) command with multiple sources

```
hoogle generate --source=local --source=stackage --source=hackage --source=file1.txt 
```

Unfortunately there doesn't appear to be a common command that works between both versions.

I also suggest when upgrading to support an override hoogle on the `$PATH`, and then switch behaviour depending on the version.

**Comment by erikd** [comment]
The use of Hoogle 4.x is also causing the tests suite to fail when building with ghc 8.4 because Hoogle 4.x doesn't build with ghc 8.4.

I think I've used the `mafia hoogle` command once (to try it out) in all the time I've used mafia. I actually prefer the web version of hoogle. Should we simply drop the `hoogle` sub command?

Update: @markhibberd says he uses the `hoogle` subcommand every day, so we need to keep it.

**Comment by etorreborre** [comment]
As a data point I also use `hoogle` a lot more on the command line (inside ghci) than on the website.

**Comment by erikd** [comment]
Ok, heard you loud and clear :).

**Comment by tmcgilchrist** [comment]
Is the fix to switch to hoogle 5.* only or support both?

**Comment by erikd** [comment]
I'd be in favor of only supporting 5.x but I'd be interested in hearing the views of others.

**Comment by tmcgilchrist** [comment]
Looking at this now.

**Comment by tmcgilchrist** [comment]
Added support for using the hoogle found on users $PATH, supports both Hoogle 4 and 5.
The basics of search and starting up a local server work. There are probably some rough edges, especially switching between 4 and 5. Please report and submit PRs if you find any. Cheers.
